
name: Cypress Test headless

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Headless Chrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
          headless: true
          record: true
    

